### ISSUE TITLE
Problems on Android

### ISSUE THREAD

**Issue by gabrielbiga** [tapio/plasma-forks#3]
Hello! Congratulations for a awesome game! But this game can run on a Android device?

**Comment by tapio** [comment]
Thanks! The game is probably too demanding for a mobile GPU/CPU (it doesn't even run that great on desktop). Even if the settings were turned down by default on Android and that would make it run adequately, controls would need to be re-implemented (no keyboard or mouse on most Androids...). I have currently no time or interest to do that, but patches are welcomed. :wink:
